# How TensorFlow Works

1. Import or generate datasets
2. Transform and normalize data. A normalisation in TF will look like this: data = tf.nn.batch_norm_with_global_normalization(...)
3. Partition datasets into train, test and validation sets
4. Set algorithm parameters (hypermarameters) like for example: learning_rate, batch_size or iterations...
5. Initialize variables and placeholders. TF needs to know what kind of data we want to send, which size it has and so on
6. Define the model structure. The model is defined in the TF Graph and describes the neural network
7. Declare the loss function. It tells us how fare off our predictions are from the actual values.
8. Initialize and train the model. 
9. Evalueate the model. Check how well our model does with new data or if its underfit or overfit.
10. Tune hyperparameters
11. Deploy/predict new outcomes

In [ ]:
import tensorflow as tf

- Create a Tensor

In [52]:
row_dim = 3
col_dim = 3

zero_tsr = tf.zeros([row_dim, col_dim])      # Zero filled Tensor
print(sess.run(zero_tsr))
print("")
ones_tsr = tf.ones([row_dim, col_dim])       # Ones filled Tensor
print(sess.run(ones_tsr))
print("")
filled_tsr = tf.fill([row_dim, col_dim],42)  # Constant filled Tensor
print(sess.run(filled_tsr))
print("")
constant_tsr = tf.constant([1,2,3])          # Constant filled Tensor
print(sess.run(constant_tsr))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[42 42 42]
 [42 42 42]
 [42 42 42]]

[1 2 3]


- Initialize a Tensor based on the shape of other Tensors

In [54]:
zeros_similar = tf.zeros_like(constant_tsr)
print(sess.run(zeros_similar))
print("")
ones_similar = tf.ones_like(constant_tsr)
print(sess.run(ones_similar))

[0 0 0]

[1 1 1]


- Create Sequence Tensors

In [56]:
linear_tsr = tf.linspace(10.0, 12.0, 3, name="linspace") # Result will be 3 numbers [10.0, 11.0, 12.0]
print(sess.run(linear_tsr))
integer_seq_tsr = tf.range(6,15,3)                       # Result will be 3 numbers [6, 9, 12], Limit value 15 not included!
print(sess.run(integer_seq_tsr))

[ 10.  11.  12.]
[ 6  9 12]


- Random Tensors

In [57]:
randunif_tsr = tf.random_uniform([row_dim,col_dim],minval=0,maxval=1) # Creates a random Tensor with uniform distribution 
#(minval <= x < maxval!!!)
print(sess.run(randunif_tsr))
print("")
randnorm_tsr = tf.random_normal([row_dim,col_dim], mean=0.0, stddev=1.0) # Creates a random Tensor with normal distribution
print(sess.run(randnorm_tsr))
print("")
runcnorm_tsr = tf.truncated_normal([row_dim,col_dim],mean=0.0,stddev=1.0) # Creates a random Tensor with normal distributon
# values whose magnitude is more than 2 standard deviations from the mean are dropped and re-picked
print(sess.run(runcnorm_tsr))
print("")
shuffled_output = tf.random_shuffle(constant_tsr) # shuffles the values of a given Tensor
print(sess.run(shuffled_output))
print("")

#cropped_image = tf.random_crop(IMAGE,[height/2,width/2,3]) # Crop an image and keep the dimensions (3 for an image)

[[ 0.03712177  0.17883742  0.63075066]
 [ 0.04665935  0.79237759  0.22698116]
 [ 0.82523584  0.48768902  0.01578248]]

[[ 1.06483698 -0.38931605  0.47574228]
 [-0.07123046 -0.34095421  1.51829422]
 [-2.79055071 -0.28556886  0.74464577]]

[[ 1.52185285  1.23052967  0.88130879]
 [-0.31831756  1.59784675  0.07216645]
 [-0.1374189  -1.84951925  1.00566757]]

[2 3 1]



- Create a Variable

In [36]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(initialize_op)

In [37]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
